name: "Create GitHub self hosted runner"
description: "Create a GitHub self hosted runner on AWS"

inputs:
  aws_region:
    description: "AWS region code"
    required: true
  iam_role_arn:
    description: "ARN of the IAM role to assume"
    required: true
  ecs_cluster_name:
    description: "ECS cluster"
    required: true
  ecs_task_definition:
    description: "ECS task definition family[:revision] or full ARN"
    required: true
  ecs_container_name:
    description: "Name of the gh runner container in the ECS task definition"
    required: true
  ecs_task_subnet_id:
    description: "ID of the subnet where the task will run"
    required: true
  ecs_task_sec_group:
    description: "ID of security group to attach to the task"
    required: true
  pat_token:
    description: "GitHub PAT token to access APIs to manage self hosted runner"
    required: true

outputs:
  runner_name:
    value: ${{ steps.create_github_runner.outputs.RUNNER_NAME }}
    description: 'Name of the self-hosted runner'

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.iam_role_arn }}

    - name: Create GitHub Runner
      id: create_github_runner
      shell: bash
      run: |
        set -eo pipefail

        REGISTRATION_TOKEN=$(curl -s \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.pat_token }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/runners/registration-token | jq ".token" -r)

        TIMESTAMP=$(date +%s)
        RUNNER_NAME="${{ github.run_id }}-${{ matrix.index }}-${TIMESTAMP}"
        GITHUB_REPOSITORY="https://github.com/${{ github.repository }}"

        echo "{\"awsvpcConfiguration\":{\"assignPublicIp\":\"DISABLED\",
            \"securityGroups\":[\"${{ inputs.ecs_task_sec_group }}\"],
            \"subnets\":[\"${{ inputs.ecs_task_subnet_id }}\"]}}" > network_config.json
        
        
        echo "{\"containerOverrides\":[{\"name\":\"${{ inputs.ecs_container_name }}\",\"environment\":[
              {\"name\":\"RUNNER_NAME\",\"value\":\"${RUNNER_NAME}\"},
              {\"name\":\"GITHUB_REPOSITORY\",\"value\":\"${GITHUB_REPOSITORY}\"},
              {\"name\":\"GITHUB_TOKEN\",\"value\":\"${REGISTRATION_TOKEN}\"},
              {\"name\":\"LABELS\",\"value\":\"${RUNNER_NAME}\"}]}]}" > overrides.json

        ECS_TASK_ID=$(aws ecs run-task \
          --launch-type "FARGATE" \
          --cluster "${{ inputs.ecs_cluster_name }}" \
          --network-configuration file://./network_config.json \
          --task-definition "${{ inputs.ecs_task_definition }}" \
          --overrides file://./overrides.json \
          | jq -r '.tasks[0].taskArn' \
          | cut -d "/" -f 3)

        echo "[INFO] Started ECS task $ECS_TASK_ID"
