name: Simple example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to update."
        type: choice
        required: true
        default: dev
        options:
          - dev
          - prod

permissions:
  contents: read
  id-token: write

jobs:
  create_runner:
    name: Create Self-Hosted Runner
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    environment: ${{ inputs.environment }}
    outputs:
      runner_name: ${{ steps.start_runner.outputs.runner_name }}

    steps:
      - name: Start GitHub Runner
        id: start_runner
        uses: pagopa/eng-github-actions-iac-template/aws/create-github-runner-aws-action@aws-runner-pin-action-version
        with:
          aws_region: ${{ vars.AWS_REGION }}
          iam_role_arn: ${{ vars.IAM_ROLE }}
          ecs_cluster_name: ${{ vars.ECS_CLUSTER_NAME }}
          ecs_task_definition: ${{ vars.ECS_TASK_DEFINITION }}
          ecs_container_name: github-runner
          ecs_task_subnet_id: ${{ vars.SUBNET_ID }}
          ecs_task_sec_group: ${{ vars.SEC_GROUP_ID }}
          pat_token: ${{ secrets.BOT_TOKEN }}

  list_s3_buckets:
    name: List S3 buckets
    runs-on: [self-hosted, "${{ needs.create_runner.outputs.runner_name }}"]
    environment: dev
    needs: create_runner
    steps:
      - name: List S3 buckets
        shell: bash
        run: aws s3 ls

  delete_runner:
    name: Delete Self-Hosted Runner
    needs: [create_runner, list_s3_buckets]
    strategy:
      fail-fast: true
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    environment: dev

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Stop Github Runner
        id: stop_runner
        uses: pagopa/eng-github-actions-iac-template/aws/remove-github-runner-aws-action@aws-runner-pin-action-version
        with:
          aws_region: ${{ vars.AWS_REGION }}
          iam_role_arn: ${{ vars.IAM_ROLE }}
          ecs_cluster_name: ${{ vars.ECS_CLUSTER_NAME }}
          pat_token: ${{ secrets.BOT_TOKEN }}
          runner_name: ${{ needs.create_runner.outputs.runner_name }}
